test: ENC[AES256_GCM,data:h1/Scw==,iv:UWZ+YZMQTfLnhLJNZ3alHVsTGRmLFH+ZQv61xuzrzlU=,tag:6714Fhlpqk5R4DT98uSmow==,type:str]
sops:
    age:
        - recipient: age1hj06ycrwgwj2we722jpghmk8uxefwmlhakvrpe7k9pvxlg2gtauqc62cw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLT1c5elVJQWROUjRaeUpL
            eU1ONWQxMjFkcDh4dm1WUkREYjlnVXhsNFZRCmN6alRXNmNaOGZSWnM5cHQxTVk2
            THJabi9Samk2Q3NXZ2p6aEVLQXh3aTAKLS0tIGlGV2NGQml4UytkTU1wSGx1L0dl
            U2RaOXcxcWlKRFl3STdCV05mWEZSTWMKitSF3c7uQbB/VnmVMbuhaJYmxq9xUOIL
            E7Vh7jznTh5dpIIQXBemThmral+WjGh8/InIBfkT68iMYKEl7spdJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qj9m662rm3zkq4tuhnsyly5uafvchduye26qak9pqwm7lzf2lqrql2twzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaWsxMlpVNm9sY2ZjN3d2
            K2h3T3lINlpNYWhlNm5WekxXbjlxZjc2Q1J3ClRRSHY3MXNKbVZTN2RsRkNsQlJ2
            ZFJHQm1xYjZVbGplM0VQT1JaMTNlL3cKLS0tIDZaSjFIY2RCWllib25GS1F0MFo0
            a0orUzZMaHdLT3NNcklqQnhsTndGN2MKebRAj0GUjrZh9jx3cRL4B+p2zkBCHwxc
            DMOwwsCOVL7idxjoTvTieDsCbjcTuwsRtAiSkn1Q6/96tAcAhWJHCg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16q3yevap8wt2yl6y0t2eq3vrp7d04xzs2f7dvvarmy3nu3wqpsjqgc8u7q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRFZONDA4QnVkMzFaTTlJ
            Nnd0VjJheTk0bVhYV2c2bjUyM0thc0lXQ0NZCkhnVFlYWVVxVDdiNUZnM3IvY3Y5
            SU0yeC9LemZ4RW5MSU43RTBTcUw5c3MKLS0tIEplYzFibi9UZzFXNXVtLzZnUTJ1
            RGhRbHIyMVF2TkxRZlZlUTkzQkJocGMKlygdd272eYZipjqcrJYor1mNC1GrmsCV
            R5OKb+K628efmx0QsxQhY+96MNoOCG31T/CdpH5yHa4/6YDsXf0PNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w486cu2ntujvmukcteeeysz98ngrxz4l5wduvpe7cw858wea4gqqxvasae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc1BRR05OZG4wVFZkMzdW
            bW50ZzE4RmE0YklZaTJ1aFZXdm1GOFBZYzAwCnRVdTJ1eDd0NjJaZnlKUHI0bG1n
            Ylp5Njh5Q3VPbWkzaU5wbksxSmhoOEEKLS0tIGdFWnBlc0Z1MlF4dFEycUY0anBG
            OE9uWjEvRFNDSnJTK2J6S08rREtpVTQKwS5HigWLqc5WoYIPbr5yvaG55JvwLD6J
            zWRTwfrbMtKKQMbJhQ7yiw+HjY2icLcvh5bm57Qxh6eMzk7sD0EnFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T18:16:44Z"
    mac: ENC[AES256_GCM,data:ynnNJnBw79qxMiZWY7lai6fl3ieF/WfPW3Y613c7DB6hZAz55F12Hz+nOL8y1Yut3JJabqH26iWiP9E6FrcnoleLgTf3eROqTTEAjWGVrExhHpesx2Ae3C9zRosv649w58hde+V7sK7G3n1jTVOIKuBvAFY9EIznhnfs225272M=,iv:6g7OwT48JQApmgITi3gi1VeGLYbpPws9i0QA7d7zckw=,tag:JDXwMBO+ebp7aEN/8dZ/Lg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
