keys:
  - &shinjuku age1qj9m662rm3zkq4tuhnsyly5uafvchduye26qak9pqwm7lzf2lqrql2twzc
  - &asakusa age16q3yevap8wt2yl6y0t2eq3vrp7d04xzs2f7dvvarmy3nu3wqpsjqgc8u7q
  - &ikebukuro age1w486cu2ntujvmukcteeeysz98ngrxz4l5wduvpe7cw858wea4gqqxvasae
  - &akihabara age1hj06ycrwgwj2we722jpghmk8uxefwmlhakvrpe7k9pvxlg2gtauqc62cw5

creation_rules:
  - path_regex: secrets/homelab/.*\.(ya?ml|json|pem)$
    key_groups:
    - age:
      - *akihabara
      - *shinjuku
      - *asakusa
      - *ikebukuro

  - path_regex: secrets/.*\.ya?ml$
    key_groups:
    - age:
      - *shinjuku
      - *asakusa
      - *ikebukuro