test1: ENC[AES256_GCM,data:uBowrw==,iv:A7GYHCe65w/zuMLEBWbqZBn5+2qnnJmf07pH4OGkGbA=,tag:dWadfkF5Oh/7At0Ph42/Yg==,type:str]
test2: ENC[AES256_GCM,data:V5g8wn0=,iv:yzPUXDgK1UnaQfdo82eASw4fqyGZQBXWhAI/1tu7tWk=,tag:LZXvu2Vuod1x/K8t0onsLA==,type:str]
sops:
    age:
        - recipient: age1qj9m662rm3zkq4tuhnsyly5uafvchduye26qak9pqwm7lzf2lqrql2twzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YXF5THdRcDVObWJuN2hE
            aktzN2RUQjdZcVppTjFUZi9EallxeTNEaHhNCng2L0lDcC92RnpSYXRDUWtwdTNp
            czdMazhhTTB3SEQybjYrVzRpbEpLMWcKLS0tIENieEhXeU1zMzBCS3A0QU1VZnZu
            MFVRTkpkeDZsOGxEZmVEWElqWGRoRFEKF0TTEZ/u0vLtWgPPQVoGvG9eJZZkaaqC
            7+R366R0eLQkthKhDMU6UU8rtsJaXfmDbuSMrQwJSeiaYO+/dVWeSg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16q3yevap8wt2yl6y0t2eq3vrp7d04xzs2f7dvvarmy3nu3wqpsjqgc8u7q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcjducWtSVVQ1V2wyUWR1
            MkZqakZoWUpqZWp4WXlaUE1iVHVNYkJ4R1hFCm5jM0RBemtQbnlrSUVXb1lPcDgv
            TGtRSUlYTkhBK2NiSUt3SHZnWnJzZDAKLS0tIGZXVHV6OUtCVHdmTUdMN3dKakhW
            ZVp4WjBZRGJSMDlkVEFncmFKdEJUcGMKS3rsyHdgxMOA2RPtQEoooMYVkDfLTR3R
            jfWSaq6mKbcuCdDHun1PIvEldaaYLDKHV+yej18I/7qAbFkWu27kug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w486cu2ntujvmukcteeeysz98ngrxz4l5wduvpe7cw858wea4gqqxvasae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMXdBbUlSNkJZeGN6V1Vi
            M1VtR1dBTlp6c1I1L2dld3ZxemNLN3BxY1dnCm5IeEhPaFd4djIvR0JJa1IxeUhs
            eGtxdC92UmpKckY0RTRrZVQzQnBGdG8KLS0tICtnVkxHVTl2K2RQaThvZTA3b2NU
            RnVxUTRIdU41R3cvZ0JYUTZCZFZ2Q0kKc5rOhLJ0TmuiKcH6Yne4mw+iSXNGE/wD
            3y3kz6Lvz86JV7Z0176b+Ex0dPGHXjrWH83lmoqUy30768Kqu0uB8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T22:22:53Z"
    mac: ENC[AES256_GCM,data:JrQ43fhwuVDQNNTpiZ5MNpkEcbIRUaOtrdeq573ZG/O0th7MpADi/gjSgJX9k7GcusxobkZIH0H5Ha3y4lRfFob7pnuOH1+6mQ7eaDyIjEncvGFML72/3XVxOJ0zWUKDwpSz+hL5EZ5oenMchIkm3edmJhZsQr/uATkmkqQ+t84=,iv:4qtldIXDHu2yjgRl+YQ7Nt7/8/R/pR0Nib2RFO0ReZE=,tag:ZEJYICM2h6WtFB1FrJaZTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
