test1: ENC[AES256_GCM,data:uBowrw==,iv:A7GYHCe65w/zuMLEBWbqZBn5+2qnnJmf07pH4OGkGbA=,tag:dWadfkF5Oh/7At0Ph42/Yg==,type:str]
test2: ENC[AES256_GCM,data:V5g8wn0=,iv:yzPUXDgK1UnaQfdo82eASw4fqyGZQBXWhAI/1tu7tWk=,tag:LZXvu2Vuod1x/K8t0onsLA==,type:str]
sops:
    age:
        - recipient: age1qj9m662rm3zkq4tuhnsyly5uafvchduye26qak9pqwm7lzf2lqrql2twzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSUxpUTRBU0pNMmx3WlNH
            UWllLzY3SkZLQldZVkphUER2WERmcUlvbG1ZCjhwbmtjekdUUG5Ic2VCNDJpS0s2
            eXphUVYzR09ldHdYKytEQVRVMzBPbEkKLS0tIHF2ZkdLd1JCSG85WTdvaHdmdVBs
            VkdKeGRKYW9Ga0kvbEc4UGNsN2tUS0kKXpAAJ6dYQHC8Um7Y+1sq71n3lo3ujGNL
            HJQJi+/MgXNoEssjPgGx7dYOaJntKAQ0s+19S/E8alVFchZIY7Rdaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T22:22:53Z"
    mac: ENC[AES256_GCM,data:JrQ43fhwuVDQNNTpiZ5MNpkEcbIRUaOtrdeq573ZG/O0th7MpADi/gjSgJX9k7GcusxobkZIH0H5Ha3y4lRfFob7pnuOH1+6mQ7eaDyIjEncvGFML72/3XVxOJ0zWUKDwpSz+hL5EZ5oenMchIkm3edmJhZsQr/uATkmkqQ+t84=,iv:4qtldIXDHu2yjgRl+YQ7Nt7/8/R/pR0Nib2RFO0ReZE=,tag:ZEJYICM2h6WtFB1FrJaZTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
